### ISSUE TITLE
Custoconnector takes data from indexed table.

### ISSUE THREAD

**Issue by KaminskiMichal** [Custobar/magento2-plugin#1]
Hello.

We use this module in our project. We have a problem where prices in Custobar and Magento are not always the same. I found that the problem is that this module takes prices from 'catalog_product_index_price' (special_price is still taken from base table) and this table is not always up-to-date. So I think this only works after the reindexing. This happens in \Custobar\CustoConnector\Helper\Data::getProductEntity method. 

Is it the known issue or maybe I'm missing something?

Thank you in advance.

**Comment by Uninen** [comment]
Hi! Is this still an issue for you? And if it is, have you tried the dev branch?

**Comment by Uninen** [comment]
Closing this as stale.
